atl_display_spend: sum
atl_ooh_spend: sum
atl_ott_spend: sum
atl_otv_spend: sum
atl_paid_social_spend: sum
atl_sem_spend: sum
atl_tv_spend: sum
ctrl_competitor_asp: mean
ctrl_competitor_npd: mean
ctrl_competitor_total_sales: mean
ctrl_macro_trscg_p: mean
ctrl_own_brand_discount_rate: mean
ctrl_own_brand_npd: mean
ctrl_top5_market_share: mean
date_key: NA
ec_dy_spend: sum
ec_jd_onsite_spend: sum
ec_tmall_onsite_spend: sum
omni_consumption: sum
tmkt_pg_spend: sum
tmkt_sampling_spend: sum
