EM_ALL_OPT_OUT_FLAG: binary
EM_COUNT_VALID: continuous
EM_MONTHS_LAST_OPEN: continuous
EM_NUM_OPEN_30: continuous
HH_AGE: continuous
HH_INCOME: continuous
IID_COUNT: continuous
POS_LAST_ORDER_DPA: binary
POS_LAST_TOTAL_REVENUE: continuous
POS_MARGIN_TOTAL: continuous
POS_MARGIN_TOTAL_12MO: continuous
POS_MNTHS_LAST_ORDER: continuous
POS_NUM_ORDERS: continuous
POS_NUM_ORDERS_24MO: continuous
POS_REVENUE_BASE: continuous
POS_REVENUE_BASE_SP_6MO: continuous
POS_REVENUE_TOTAL: continuous
POS_REVENUE_TOTAL_6MO: continuous
POS_SP_QTY_24MO: continuous
POS_TOT_REVPERSYS: continuous
SH_INQUIRED_LAST12MO: binary
SH_INQUIRED_LAST3MO: binary
SH_MNTHS_LAST_INQUIRED: continuous
WEB_CNT_IID_ACCESSED: continuous
WEB_MNTHS_SINCE_LAST_SES: continuous
dv_balance: exclude
dv_response: target
id: continuous
pos_mo_btwn_fst_lst_order: continuous
