baby_age_first_order: continuous
baby_age_last_order: continuous
baby_residual_lifecycle: continuous
cltv: continuous
customer_lifecycle: continuous
customer_lifecycle_finished_flag: nominal
dac_id: id
first_order_channel: nominal
first_order_channel_grp: binary
first_order_jar: continuous
first_order_province: nominal
first_order_province_grp: nominal
first_repurchase_interval: continuous
frisomum: binary
gold: binary
last_repurchase_interval: continuous
order_conversion_jar: continuous
prestige: binary
reg_channel: nominal
reg_channel_grp: nominal
stage_f0: binary
stage_f1: binary
stage_f2: binary
stage_f3: binary
stage_f4: binary
